version: '3'

services:
  backend:
    build: ./backend
    ports:
      - "4000:4000"
    command: node index.js          
    environment:
      - NODE_ENV=production

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production